/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Artists: typeof import('./src/components/Pages/artists.vue')['default']
    Bangdan: typeof import('./src/components/Pages/bangdan.vue')['default']
    Boke: typeof import('./src/components/Pages/dj.vue')['default']
    Dj: typeof import('./src/components/Pages/dj.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Loading: typeof import('./src/components/loading/index.vue')['default']
    Music: typeof import('./src/components/Pages/music.vue')['default']
    Mv: typeof import('./src/components/Pages/mv.vue')['default']
    Recommand: typeof import('./src/components/recommand/index.vue')['default']
    Remen: typeof import('./src/components/Pages/remen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./src/components/Scroll/index.vue')['default']
    SearchResult: typeof import('./src/components/SearchPages/SearchResult/index.vue')['default']
    Singer: typeof import('./src/components/SearchPages/SearchResult/conponents/singer.vue')['default']
    Slider: typeof import('./src/components/Slider/index.vue')['default']
    SongBlock: typeof import('./src/components/SongBlock/index.vue')['default']
    Songs: typeof import('./src/components/SearchPages/SearchResult/conponents/songs.vue')['default']
    Suggestion: typeof import('./src/components/SearchPages/suggestion.vue')['default']
    Tab: typeof import('./src/components/Tabs/Tab.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar/index.vue')['default']
    Toast: typeof import('./src/components/Toast/index.vue')['default']
    User: typeof import('./src/components/SearchPages/SearchResult/conponents/user.vue')['default']
  }
}
